name: Build LineageOS

on: CI

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ROM_NAME: lineage
      ROM_VERSION: 21.0
      DEVICE: mido
      DEVICE_TREE_URL: https://github.com/zeelog/android_device_xiaomi_mido
      KERNEL_TREE_URL: https://github.com/zeelog/android_kernel_xiaomi_mido
      VENDOR_TREE_URL: https://github.com/zeelog/proprietary_vendor_xiaomi

    steps:
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install openjdk-11-jdk -y

    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Sync ROM sources
      run: |
        git clone https://github.com/LineageOS/android.git -b lineage-21.0 --depth 1
        cd android
        repo init -u https://github.com/LineageOS/android.git -b lineage-21.0
        repo sync -c -j$(nproc --all)

    - name: Sync device tree
      run: |
        cd android
        git clone $DEVICE_TREE_URL device/$DEVICE

    - name: Sync kernel tree
      run: |
        cd android
        git clone $KERNEL_TREE_URL kernel/$DEVICE

    - name: Sync vendor tree
      run: |
        cd android
        git clone $VENDOR_TREE_URL vendor/$DEVICE

    - name: Build ROM
      run: |
        cd android
        source build/envsetup.sh
        lunch lineage_$DEVICE-userdebug
        mka bacon -j$(nproc --all)

    - name: Upload ROM
      uses: actions/upload-artifact@v2
      with:
        name: lineageos
        path: |
          android/out/target/product/$DEVICE/*.zip
          android/out/target/product/$DEVICE/*.img
