name: Test Local Manifest

# Allows the workflow to be triggered manually
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up repo
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize repo
        run: |
          repo init -u https://github.com/Hassan-kareem/local_manifests.git -b 20.0-mido
      
      - name: Sync repo
        run: |
          repo sync --force-sync --no-clone-bundle --no-tags --prune
      
      - name: Validate manifest
        run: |
          # You can add additional validation scripts here if needed.
          echo "Manifest synced successfully!"
